### ISSUE TITLE
Returned by server pipeName is null

### ISSUE THREAD

**Issue by juergstaub** [HavenDV/H.Pipes#20]
### Describe the bug

We are sporadically seeing the following exception when connecting > 1 pipeclient with pipeClient.ConnectAsync()

`System.InvalidOperationException: Connection failed: Returned by server pipeName is null
   at H.Pipes.PipeClient`1.GetConnectionPipeName(CancellationToken cancellationToken)
   at H.Pipes.PipeClient`1.GetConnectionPipeName(CancellationToken cancellationToken)
   at H.Pipes.PipeClient`1.ConnectAsync(CancellationToken cancellationToken)` 

Clients are connected in a relatively short time, the problem is already visible with 3 clients, but does not happen all the time.

### Steps to reproduce the bug

Create pipe server
Create multiple pipe clients

### Expected behavior

All pipe clients connect normally and without ab exception

### NuGet package version

<PackageReference Include="H.Pipes" Version="2.0.37" />

### Platform

Console

### IDE

Other

**Comment by juergstaub** [comment]
I able to mitigate the problem by adding a random delay before ConnectAsync:
`                var r = new Random();
                await Task.Delay(r.Next(2000, 5000));
                await pipeClient.ConnectAsync();
`

**Comment by HavenDV** [comment]
Thanks for the problem and detailed description. Yes, indeed, the main pipe of the server accepts requests one at a time, and there may be problems with simultaneous requests from several clients.

Comments for correction (to me in the future or anyone who wants to do this):
- We need to create a test to test this by trying to connect as many clients at the same time as is guaranteed to throw an exception.

I'll get into this after checking out this PR - https://github.com/HavenDV/H.Pipes/pull/19 because it changes the code a lot.

**Comment by HavenDV** [comment]
Closing this as fixed/stale. This was reported against 2.0.37, and the current connection tests cover multi-target client/server startup without reproducing the null pipe-name failure. Please open a fresh issue with current package versions if it still occurs.
