### ISSUE TITLE
Application getting terminated

### ISSUE THREAD

**Issue by ajith-karkera** [HavenDV/H.Pipes#26]
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileLoadException
   at System.Threading.Tasks.ValueTask.get_IsCompleted()
   at H.Pipes.PipeClient`1+<DisconnectInternalAsync>d__48[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at H.Pipes.PipeClient`1+<<ConnectAsync>b__46_0>d[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

**Comment by HavenDV** [comment]
Can you provide a project or code that reproduces this exception? At the moment I don't have enough information to understand the problem

**Comment by ajith-karkera** [comment]
Hi @HavenDV ,

Below is the code snippet:

PipeClient<Model> m_client = new PipeClient<Model>("NamedPipeServer", formatter: new NewtonsoftJsonFormatter(), reconnectionInterval: new TimeSpan(0, 0, 0, 0, 100));
m_client.MessageReceived += OnMessageReceived;
m_client.ExceptionOccurred += OnExceptionOccurred;
m_client.Connected += OnConnected;
m_client.Disconnected += OnDisconnected;
m_client.AutoReconnect = true;
await m_client.ConnectAsync();
await Task.Delay(Timeout.InfiniteTimeSpan);

**Comment by ajith-karkera** [comment]
Hi @HavenDV ,
Any update on the issue?

**Comment by HavenDV** [comment]
> Hi @HavenDV , Any update on the issue?

Please check [2.0.42](https://www.nuget.org/packages/H.Pipes/2.0.42)

**Comment by ajith-karkera** [comment]
Hi @HavenDV ,

We dont see the above issue anymore, But the below .NET Runtime error:

Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c00000fd, exception address 00007FFC97D5A8C7

**Comment by HavenDV** [comment]
Closing this as stale without enough information to diagnose. The FileLoadException stack is from an old package/runtime combination, and current local verification builds and tests the repository on net4.8 and net9.0. Please open a new issue with exact package versions and a minimal repro if this still happens.
